### ISSUE TITLE
[feat] Write out full user name

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/hpc-access#170]
### What is your feature request?

We need to write the user's full name "FIRSTNAME LASTNAME" out as "full_name" in the `hpcusers` REST API.

### Have you seen anything similar somewhere else?

They did a similar thing!

**Comment by stolpeo** [comment]
SlugRelatedField with `name` as full name or `first_name` `last_name`.

**Comment by stolpeo** [comment]
`phone_number`
